# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ratPacket.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ratPacket.proto',
  package='cyber_project',
  syntax='proto2',
  serialized_pb=_b('\n\x0fratPacket.proto\x12\rcyber_project\"c\n\x06Packet\x12\x11\n\tseqNumber\x18\x01 \x02(\x05\x12%\n\x06opcode\x18\x02 \x02(\x0e\x32\x15.cyber_project.Opcode\x12\x0e\n\x06isLast\x18\x03 \x02(\x08\x12\x0f\n\x07\x63ontent\x18\x04 \x02(\x0c*+\n\x06Opcode\x12\x0b\n\x07\x45XECUTE\x10\x00\x12\n\n\x06UPDATE\x10\x01\x12\x08\n\x04\x46ILE\x10\x02')
)

_OPCODE = _descriptor.EnumDescriptor(
  name='Opcode',
  full_name='cyber_project.Opcode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='EXECUTE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UPDATE', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FILE', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=135,
  serialized_end=178,
)
_sym_db.RegisterEnumDescriptor(_OPCODE)

Opcode = enum_type_wrapper.EnumTypeWrapper(_OPCODE)
EXECUTE = 0
UPDATE = 1
FILE = 2



_PACKET = _descriptor.Descriptor(
  name='Packet',
  full_name='cyber_project.Packet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='seqNumber', full_name='cyber_project.Packet.seqNumber', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='opcode', full_name='cyber_project.Packet.opcode', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='isLast', full_name='cyber_project.Packet.isLast', index=2,
      number=3, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='content', full_name='cyber_project.Packet.content', index=3,
      number=4, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=133,
)

_PACKET.fields_by_name['opcode'].enum_type = _OPCODE
DESCRIPTOR.message_types_by_name['Packet'] = _PACKET
DESCRIPTOR.enum_types_by_name['Opcode'] = _OPCODE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Packet = _reflection.GeneratedProtocolMessageType('Packet', (_message.Message,), dict(
  DESCRIPTOR = _PACKET,
  __module__ = 'ratPacket_pb2'
  # @@protoc_insertion_point(class_scope:cyber_project.Packet)
  ))
_sym_db.RegisterMessage(Packet)


# @@protoc_insertion_point(module_scope)
